"""empty message

Revision ID: 06197b16838b
Revises: 92e9ef6ddd3c
Create Date: 2017-09-15 12:08:51.198879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06197b16838b'
down_revision = '92e9ef6ddd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuition_blueprint_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('qbo_id', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuition_blueprint_school')
    # ### end Alembic commands ###
