"""empty message

Revision ID: 12fc1d203f36
Revises: 7c8aa0394cb1
Create Date: 2017-09-21 08:23:32.919509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fc1d203f36'
down_revision = '7c8aa0394cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_blueprint_recurring_payment', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuition_blueprint_recurring_payment', 'start_date')
    # ### end Alembic commands ###
