"""empty message

Revision ID: 528065b88706
Revises: 06197b16838b
Create Date: 2017-09-19 09:10:34.899263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '528065b88706'
down_revision = '06197b16838b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuition_blueprint_school')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuition_blueprint_school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('qbo_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'tuition_blueprint_school_pkey')
    )
    # ### end Alembic commands ###
