"""empty message

Revision ID: 7c8aa0394cb1
Revises: 53d38cf80599
Create Date: 2017-09-19 13:59:19.192487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8aa0394cb1'
down_revision = '53d38cf80599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_blueprint_recurring_payment', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuition_blueprint_recurring_payment', 'end_date')
    # ### end Alembic commands ###
