"""empty message

Revision ID: 92e9ef6ddd3c
Revises: 6e6d6b5bd8be
Create Date: 2017-09-07 11:19:26.132871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e9ef6ddd3c'
down_revision = '6e6d6b5bd8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorize_qbo_blueprint_authentication_tokens', sa.Column('access_token', sa.String(length=1024), nullable=True))
    op.drop_column('authorize_qbo_blueprint_authentication_tokens', 'oauth_token_secret')
    op.drop_column('authorize_qbo_blueprint_authentication_tokens', 'oauth_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorize_qbo_blueprint_authentication_tokens', sa.Column('oauth_token', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('authorize_qbo_blueprint_authentication_tokens', sa.Column('oauth_token_secret', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('authorize_qbo_blueprint_authentication_tokens', 'access_token')
    # ### end Alembic commands ###
