"""empty message

Revision ID: d2aa9022cdc7
Revises: 528065b88706
Create Date: 2017-09-19 09:13:47.456876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2aa9022cdc7'
down_revision = '528065b88706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuition_blueprint_recurring_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.String(length=120), nullable=True),
    sa.Column('bank_account_id', sa.String(length=120), nullable=True),
    sa.Column('credit_card_id', sa.String(length=120), nullable=True),
    sa.Column('item_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuition_blueprint_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('qbo_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('recurring_payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recurring_payment_id'], ['tuition_blueprint_recurring_payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuition_blueprint_payment')
    op.drop_table('tuition_blueprint_recurring_payment')
    # ### end Alembic commands ###
