"""empty message

Revision ID: ed8fc7aebf25
Revises: 38d00f17ffb7
Create Date: 2017-08-24 14:15:38.027965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8fc7aebf25'
down_revision = '38d00f17ffb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_tc_to_qbo_blueprint_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('tc_school_id', sa.Integer(), nullable=True),
    sa.Column('qbo_company_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_tc_to_qbo_blueprint_school')
    # ### end Alembic commands ###
