import os

GSUITE_SERVICE_ACCOUNT_CREDENTIALS=os.environ.get('GSUITE_SERVICE_ACCOUNT_CREDENTIALS', None)
TEACHERS_SCHOOLS_TEMPLATES_FOLDER_ID=os.environ.get('TEACHERS_SCHOOLS_TEMPLATES_FOLDER_ID', None)
TEACHERS_SCHOOLS_LIVE_FOLDER_ID=os.environ.get('TEACHERS_SCHOOLS_LIVE_FOLDER_ID', None)
