import os

QBO_CLIENT_ID = os.environ['QBO_CLIENT_ID']
QBO_CLIENT_SECRET = os.environ['QBO_CLIENT_SECRET']
QBO_ACCOUNTING_API_BASE_URL = os.environ['QBO_ACCOUNTING_API_BASE_URL']
QBO_PAYMENTS_API_BASE_URL = os.environ['QBO_PAYMENTS_API_BASE_URL']
