import os

QBO_CONSUMER_KEY = os.environ['QBO_CONSUMER_KEY']
QBO_CONSUMER_SECRET = os.environ['QBO_CONSUMER_SECRET']
QBO_ACCOUNTING_API_BASE_URL = os.environ['QBO_ACCOUNTING_API_BASE_URL']
QBO_PAYMENTS_API_BASE_URL = os.environ['QBO_PAYMENTS_API_BASE_URL']
